.TH "_ExampleGenerator_" 3 "28 Jul 2003" "VFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ExampleGenerator_ \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Holds the information needed to reproducibly make a random data set. See \fBExampleGenerator.h\fP for more detail. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VFML from the source code.
