.TH "Belief Net Section" 3 "28 Jul 2003" "VFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Belief Net Section \- 
.SH "Detailed Description"
.PP 
All of these are related to the use and construction of belief nets. 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBeliefNet.h\fP"
.br
.RI "\fIA Belief Net Structure with CPT local models. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBbeliefnetcorrupt\fP"
.br
.RI "\fIMakes some random changes to a BeliefNet. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBbeliefnetdata\fP"
.br
.RI "\fICreates a data set by sampling from a Bayesian Network. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBbeliefnetscore\fP"
.br
.RI "\fITests a BeliefNet in several ways. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBbnlearn\fP"
.br
.RI "\fILearns the structure of a BeliefNet from a data set. Designed to be easily modified. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBbnlearn-engine.h\fP"
.br
.RI "\fILearn the structure of a BeliefNet from data. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBExample.h\fP"
.br
.RI "\fIADT for training (and testing, etc.) data. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBExampleSpec.h\fP"
.br
.RI "\fISchema for training data. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBvfbn1\fP"
.br
.RI "\fILearns the structure of a BeliefNet from a very large data set using sampling. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBvfbn2\fP"
.br
.RI "\fILearns the structure of a BeliefNet from a very large data set using sampling and a new search proceedure. \fP"
.PP

.in -1c
