.TH "bug" 3 "28 Jul 2003" "VFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List
 
.IP "\fBGlobal \fBBNNodeStructureEqual\fP(BeliefNetNode bnn, BeliefNetNode otherNode) \fP" 1c
Only returns 1 if the parents are in the same order, but the order probably shouldn't matter. 
.PP
.PP
 
.IP "\fBFile \fBExampleSpec.h\fP \fP" 1c
Under Cygnus (and windows) lex doesn't seem to do the right thing with EOF rules, so you need to put an extra return at the end of your .names files. 
.PP

