.TH "Clustering Section" 3 "28 Jul 2003" "VFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clustering Section \- 
.SH "Detailed Description"
.PP 
All of these are related to clustering. 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBExample.h\fP"
.br
.RI "\fIADT for training (and testing, etc.) data. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBExampleSpec.h\fP"
.br
.RI "\fISchema for training data. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBkmeans\fP"
.br
.RI "\fIPerforms k-means clustering. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBvfem\fP"
.br
.RI "\fIPerforms EM clustering. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBvfkm\fP"
.br
.RI "\fIPerforms k-means clustering accelerated with sampling. \fP"
.PP

.in -1c
