.TH "FloatListPtr" 3 "28 Jul 2003" "VFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FloatListPtr \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
An ADT for a list that holds floats. 

See \fBlists.h\fP for more detail. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for VFML from the source code.
