.TH "thanks" 3 "28 Jul 2003" "VFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thanks \- Thanks
 
.IP "\fBpage \fBVFML\fP \fP" 1c
VFML was made possible by a gift from the Ford Motor Company. 
.PP
.PP
 
.IP "\fBFile \fBbindata\fP \fP" 1c
to Chun-Hsiang Hung for doing the core development work for this tool. 
.PP
.PP
 
.IP "\fBFile \fBbnlearn\fP \fP" 1c
to Matthew Richardson for making substantial optimizations to the bnlearn program. 
.PP
.PP
 
.IP "\fBFile \fBbnlearn-engine.h\fP \fP" 1c
to Matthew Richardson for extracting this interface from the bnlearn learner. 
.PP
.PP
 
.IP "\fBFile \fBcleandata\fP \fP" 1c
to Chun-Hsiang Hung for doing the core development work for this tool. 
.PP
.PP
 
.IP "\fBFile \fBcvfdt\fP \fP" 1c
to Laurie Spencer for doing the core development work for cvfdt. 
.PP
.PP
 
.IP "\fBFile \fBHashTable.h\fP \fP" 1c
to Chun-Hsiang Hung for implementing the \fBHashTable\fP ADT. 
.PP

