.TH "Utility APIs" 3 "28 Jul 2003" "VFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utility APIs \- 
.SH "Detailed Description"
.PP 
Some utility code that is used by VFML. You may find it useful or not. If you plan on modifying the internals of VFML you will certainly care about these. (There are a few places where some of these are exposed in an API too.) 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbitfield.h\fP"
.br
.RI "\fICompactly represent a bit field. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBDebug.h\fP"
.br
.RI "\fIA set of functions that help your programs produce debugging output in a consistent way. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBHashTable.h\fP"
.br
.RI "\fIA hash table. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBlists.h\fP"
.br
.RI "\fIGeneric list functions. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBmemory.h\fP"
.br
.RI "\fITracks the size of allocations made. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBrandom.h\fP"
.br
.RI "\fIGenerates random numbers in a number of ways, and has support for saving and restoring the state of the random number generator. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBstats.h\fP"
.br
.RI "\fISome statistical functions. \fP"
.PP

.in -1c
